[package]
name = "network_listener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.35.0"
pcap = "2.2.0"
chrono = "0.4.19"
log = "0.4.14"
env_logger = "0.11.5"
serde = { version = "1.0.210", features = ["derive"] }
clap = { version = "4.0.18", features = ["derive"] }
serde_json = "1.0.68"
fern = "0.6.2"
tokio = { version = "1.10.0", features = ["full"] }
pcap-async = "0.4.1"
libc = "0.2.125"