[package]
name = "network_listener"
version = "0.1.0"
edition = "2021"
description = "A packet sniffing tool for network traffic analysis and bandwidth estimation."
build = "build.rs"

[[bin]]
name = "network_listener"
path = "src/main.rs"

[[bin]]
name = "bwclient"
path = "src/prost_net/bandwidth_client.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.35.0"
pcap = "2.2.0"
chrono = "0.4.39"
log = "0.4.25"
env_logger = "0.11.6"
# serde = { version = "1.0.217", features = ["derive"] }
clap = { version = "4.5.23", features = ["derive"] }
# serde_json = "1.0.134"
fern = "0.7.1"
tokio = { version = "1.42.0", features = ["full"] }
pcap-async = "0.4.1"
libc = "0.2.169"
# bitflags = "2.6.0"
procfs = "0.17.0"
rtnetlink = "0.14.1"
neli-wifi = { version = "0.6.0", features = ["async"] }
mac_address = "1.1.7"
# neli = { version = "0.6.4", features = ["async"] }
prost = "0.13.4"
prost-types = "0.13.4"
anyhow = "1.0.95"
serde = { version = "1.0.134", features = ["derive"] }
serde_json = "1.0.64"
tonic = "*"


[build-dependencies]
tonic-build = "*"
#prost-build = "0.13.4"
