CREATE TABLE link_state (
    id SERIAL PRIMARY KEY,
    sender_ip TEXT NOT NULL,
    receiver_ip TEXT NOT NULL,
    thp_in DOUBLE PRECISION,
    thp_out DOUBLE PRECISION,
    bw DOUBLE PRECISION,
    abw DOUBLE PRECISION,
    latency DOUBLE PRECISION,
    delay DOUBLE PRECISION,
    jitter DOUBLE PRECISION,
    loss DOUBLE PRECISION,
    ts TIMESTAMPTZ NOT NULL
);

