
[listener]
iperf_server_port = 5201
bw_server_port = 40042

[server]
ip_addr = "172.16.0.254"
port = 50041

[clients]

[clients.100120]
ip_addr = "10.0.1.20"
iface = "eth0"

[clients.100121]
ip_addr = "10.0.1.21"
iface = "eth0"

[clients.100220]
ip_addr = "10.0.2.20"
iface = "eth0"

[clients.100221]
ip_addr = "10.0.2.21"
iface = "eth0"

[clients.100320]
ip_addr = "10.0.3.20"
iface = "eth0"

[clients.100321]
ip_addr = "10.0.3.21"
iface = "eth0"