[client]
iface = "eth0"
listen_port = 40042
link_phy_cap = 10000000
measurement_window = 35
tstamp_type = "adapter"


[server]
ip = "172.16.0.254"
port = 50041
send_rtts = false
send_link_states = true
probe_technique = "iperf3" # "iperf3" or "pathload"
